// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	smtpDomain "backend-skeleton-golang/commons/domain/smtp"

	mock "github.com/stretchr/testify/mock"
)

// ISmtpService is an autogenerated mock type for the ISmtpService type
type ISmtpService struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *ISmtpService) Send(_a0 smtpDomain.SendArgs) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(smtpDomain.SendArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewISmtpService interface {
	mock.TestingT
	Cleanup(func())
}

// NewISmtpService creates a new instance of ISmtpService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISmtpService(t mockConstructorTestingTNewISmtpService) *ISmtpService {
	mock := &ISmtpService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
