package msgDomain

type IMsg struct {
	ERR_NOT_FOUND                 string
	ERR_ID_ALREADY_EXISTS         string
	ERR_EMAIL_ALREADY_EXISTS      string
	ERR_SAVING_IN_DATABASE        string
	ERR_EMAIL_OR_PASSWORD_INVALID string
	ERR_INTERNAL_SERVER           string
	ERR_SMTP_SERVER               string
	ERR_TOKEN_INVALID             string

	SUCCESS_PASSWORD_UPDATED         string
	SUCCESS_REQUEST_RESTORE_PASSWORD string
}

var Msg IMsg

func New() {
	Msg = IMsg{
		ERR_NOT_FOUND:                    "ERR_NOT_FOUND",
		ERR_ID_ALREADY_EXISTS:            "ERR_ID_ALREADY_EXISTS",
		ERR_EMAIL_ALREADY_EXISTS:         "ERR_EMAIL_ALREADY_EXISTS",
		ERR_SAVING_IN_DATABASE:           "ERR_SAVING_IN_DATABASE",
		ERR_EMAIL_OR_PASSWORD_INVALID:    "ERR_EMAIL_OR_PASSWORD_INVALID",
		ERR_INTERNAL_SERVER:              "ERR_INTERNAL_SERVER",
		ERR_SMTP_SERVER:                  "ERR_SMTP_SERVER",
		ERR_TOKEN_INVALID:                "ERR_TOKEN_INVALID",
		SUCCESS_PASSWORD_UPDATED:         "SUCCESS_PASSWORD_UPDATED",
		SUCCESS_REQUEST_RESTORE_PASSWORD: "SUCCESS_REQUEST_RESTORE_PASSWORD",
	}

}
